theme: jekyll-theme-minimal

minimal_mistakes_skin    : "default" 
# Site Settings
locale                   : "ja"
title                    : Keita Kume 
description              : Ph.D student at Tokyo Institute of Technology, JSPS research fellow (DC1)

plugins:
 - jekyll-sitemap
