theme: jekyll-theme-minimal

minimal_mistakes_skin    : "default" 
# Site Settings
locale                   : "ja"
title                    : Keita Kume (久米啓太)
description              : Master student at Tokyo Institute of Technology (東京工業大学).

plugins:
 - jekyll-sitemap
